In [2]:
import pandas as pd
import numpy as np
import sqlite3
from sqlalchemy import create_engine

### clean nav_history

In [3]:
nav=pd.read_csv("data/raw/02_nav_history.csv")
nav.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [4]:
nav.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  object
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.1+ MB

In [5]:
nav.isnull().sum()

amfi_code    0
date         0
nav          0
dtype: int64

In [6]:
nav.duplicated().sum()

np.int64(0)

In [7]:
nav["date"]= pd.to_datetime(nav["date"])

In [9]:
nav=nav.sort_values(["amfi_code","date"])

In [10]:
nav=nav[nav["nav"]>0]

In [11]:
nav.head()

      amfi_code       date       nav
5750     100016 2022-01-03  520.4608
5751     100016 2022-01-04  515.0971
5752     100016 2022-01-05  521.7239
5753     100016 2022-01-06  515.7880
5754     100016 2022-01-07  515.1639

In [12]:
nav["amfi_code"].unique()

array([100016, 100025, 100033, 101206, 101207, 101208, 102885, 102886,
       102887, 118632, 118633, 118634, 118635, 118636, 119092, 119093,
       119094, 119095, 119120, 119551, 119552, 119598, 119599, 120503,
       120504, 120505, 120506, 120507, 120841, 120842, 120843, 120844,
       125497, 125498, 148567, 148568, 148569, 149322, 149323, 149324])

In [13]:
nav.to_csv("data/processed/clean_nav.csv", index=False)

print("clean_nav.csv saved successfully!")

clean_nav.csv saved successfully!

In [14]:
nav.info()

<class 'pandas.core.frame.DataFrame'>
Index: 46000 entries, 5750 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  datetime64[ns]
 2   nav        46000 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 1.4 MB

### Cleaning investor_transactions.csv

In [15]:
transactions = pd.read_csv("data/raw/08_investor_transactions.csv")

transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [16]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  object
 1   transaction_date    32778 non-null  object
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  object
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  object
 6   city                32778 non-null  object
 7   city_tier           32778 non-null  object
 8   age_group           32778 non-null  object
 9   gender              32778 non-null  object
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  object
 12  kyc_status          32778 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 3.3+ MB

In [17]:
print(transactions.columns)

Index(['investor_id', 'transaction_date', 'amfi_code', 'transaction_type',
       'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender',
       'annual_income_lakh', 'payment_mode', 'kyc_status'],
      dtype='object')

In [18]:
transactions.isnull().sum()

investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

In [19]:
transactions.duplicated().sum()

np.int64(0)

In [20]:
transactions["transaction_date"] = pd.to_datetime(transactions["transaction_date"],errors="coerce"
)

In [21]:
transactions = transactions[transactions["amount_inr"] > 0]

In [22]:
transactions["kyc_status"] = (transactions["kyc_status"].str.strip().str.upper())

In [23]:
transactions = transactions.drop_duplicates()

transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,VERIFIED
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,VERIFIED
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,VERIFIED
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,PENDING
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,PENDING

In [25]:
transactions.to_csv( "data/processed/clean_transactions.csv",index=False)

print("clean_transactions.csv saved successfully!")

clean_transactions.csv saved successfully!

In [26]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  object
 1   transaction_date    32778 non-null  datetime64[ns]
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  object
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  object
 6   city                32778 non-null  object
 7   city_tier           32778 non-null  object
 8   age_group           32778 non-null  object
 9   gender              32778 non-null  object
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  object
 12  kyc_status          32778 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(9)
memory usage: 3.3+ MB

In [27]:
transactions["transaction_type"].value_counts()

transaction_type
SIP           19716
Lumpsum        8095
Redemption     4967
Name: count, dtype: int64

In [28]:
transactions["kyc_status"].value_counts()

kyc_status
VERIFIED    30146
PENDING      2632
Name: count, dtype: int64

### cleaning scheme_performance.csv

In [29]:
performance = pd.read_csv("data/raw/07_scheme_performance.csv")

performance.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [33]:
performance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     object
 2   fund_house          40 non-null     object
 3   category            40 non-null     object
 4   plan                40 non-null     object
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     object
dtypes: float64(11), int64(3), object(5)
memory usage: 6.1+ KB

In [30]:
print(performance.columns)

Index(['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan',
       'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct',
       'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio',
       'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct',
       'morningstar_rating', 'risk_grade'],
      dtype='object')

In [32]:
performance.isnull().sum()
performance.duplicated().sum()

np.int64(0)

In [34]:
import pandas as pd

performance = pd.read_csv("data/raw/07_scheme_performance.csv")

print("Missing Values:")
print(performance.isnull().sum())


print("\nDuplicate Rows:", performance.duplicated().sum())

valid_expense = performance[(performance["expense_ratio_pct"] >= 0.1) &(performance["expense_ratio_pct"] <= 2.5)]

print("\nValid Expense Ratio Records:", len(valid_expense))

negative_sharpe = performance[performance["sharpe_ratio"] < 0]

print("Negative Sharpe Ratio Records:", len(negative_sharpe))

Missing Values:
amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

Duplicate Rows: 0

Valid Expense Ratio Records: 40
Negative Sharpe Ratio Records: 0

In [35]:
performance.to_csv("data/processed/clean_performance.csv", index=False)

print("clean_performance.csv saved successfully!")

clean_performance.csv saved successfully!

###  aum_by_fund_house.csv

In [36]:
aum = pd.read_csv("data/raw/03_aum_by_fund_house.csv")

print(aum.columns)

Index(['date', 'fund_house', 'aum_lakh_crore', 'aum_crore', 'num_schemes'], dtype='object')

In [37]:
aum.info()

print("\nMissing Values")
print(aum.isnull().sum())

print("\nDuplicate Rows")
print(aum.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            90 non-null     object
 1   fund_house      90 non-null     object
 2   aum_lakh_crore  90 non-null     float64
 3   aum_crore       90 non-null     int64
 4   num_schemes     90 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 3.6+ KB

Missing Values
date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64

Duplicate Rows
0

In [38]:
aum["date"] = pd.to_datetime(aum["date"])

In [39]:
aum = aum[(aum["aum_crore"] > 0) & (aum["aum_lakh_crore"] > 0)]

In [40]:
aum.to_csv("data/processed/clean_aum.csv", index=False)

print(" clean_aum.csv saved successfully!")

 clean_aum.csv saved successfully!

### monthly_sip_inflows.csv

In [42]:
sip = pd.read_csv("data/raw/04_monthly_sip_inflows.csv")

print(sip.columns)

Index(['month', 'sip_inflow_crore', 'active_sip_accounts_crore',
       'new_sip_accounts_lakh', 'sip_aum_lakh_crore', 'yoy_growth_pct'],
      dtype='object')

In [43]:
sip.info()

print("\nMissing Values")
print(sip.isnull().sum())

print("\nDuplicate Rows")
print(sip.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      48 non-null     object
 1   sip_inflow_crore           48 non-null     int64
 2   active_sip_accounts_crore  48 non-null     float64
 3   new_sip_accounts_lakh      48 non-null     float64
 4   sip_aum_lakh_crore         48 non-null     float64
 5   yoy_growth_pct             36 non-null     float64
dtypes: float64(4), int64(1), object(1)
memory usage: 2.4+ KB

Missing Values
month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64

Duplicate Rows
0

In [44]:
sip["month"] = pd.to_datetime(sip["month"])

In [45]:
sip["yoy_growth_pct"] = sip["yoy_growth_pct"].ffill()

In [46]:
sip = sip[sip["sip_inflow_crore"] > 0]

In [47]:
sip.to_csv("data/processed/clean_sip_inflows.csv", index=False)

### category_inflows.csv

In [48]:
category = pd.read_csv("data/raw/05_category_inflows.csv")

print(category.columns)

Index(['month', 'category', 'net_inflow_crore'], dtype='object')

In [49]:
category.info()

print("\nMissing Values")
print(category.isnull().sum())

print("\nDuplicate Rows")
print(category.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   month             144 non-null    object
 1   category          144 non-null    object
 2   net_inflow_crore  144 non-null    float64
dtypes: float64(1), object(2)
memory usage: 3.5+ KB

Missing Values
month               0
category            0
net_inflow_crore    0
dtype: int64

Duplicate Rows
0

In [50]:
category["month"] = pd.to_datetime(category["month"])

In [51]:
category.to_csv("data/processed/clean_category_inflows.csv", index=False)

### industry_folio_count.csv

In [52]:
folio = pd.read_csv("data/raw/06_industry_folio_count.csv")

print(folio.columns)

Index(['month', 'total_folios_crore', 'equity_folios_crore',
       'debt_folios_crore', 'hybrid_folios_crore', 'others_folios_crore'],
      dtype='object')

In [53]:
folio.info()

print("\nMissing Values")
print(folio.isnull().sum())

print("\nDuplicate Rows")
print(folio.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   month                21 non-null     object
 1   total_folios_crore   21 non-null     float64
 2   equity_folios_crore  21 non-null     float64
 3   debt_folios_crore    21 non-null     float64
 4   hybrid_folios_crore  21 non-null     float64
 5   others_folios_crore  21 non-null     float64
dtypes: float64(5), object(1)
memory usage: 1.1+ KB

Missing Values
month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

Duplicate Rows
0

In [54]:
folio["month"] = pd.to_datetime(folio["month"])
folio = folio[
    (folio["total_folios_crore"] > 0) &
    (folio["equity_folios_crore"] > 0) &
    (folio["debt_folios_crore"] > 0) &
    (folio["hybrid_folios_crore"] > 0) &
    (folio["others_folios_crore"] > 0)
]

In [55]:
folio.to_csv("data/processed/clean_folio_count.csv", index=False)

### portfolio_holdings.csv

In [56]:
holdings = pd.read_csv("data/raw/09_portfolio_holdings.csv")

print(holdings.columns)

Index(['amfi_code', 'stock_symbol', 'stock_name', 'sector', 'weight_pct',
       'market_value_cr', 'current_price_inr', 'portfolio_date'],
      dtype='object')

In [57]:
holdings.info()

print("\nMissing Values")
print(holdings.isnull().sum())

print("\nDuplicate Rows")
print(holdings.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   amfi_code          322 non-null    int64
 1   stock_symbol       322 non-null    object
 2   stock_name         322 non-null    object
 3   sector             322 non-null    object
 4   weight_pct         322 non-null    float64
 5   market_value_cr    322 non-null    float64
 6   current_price_inr  322 non-null    float64
 7   portfolio_date     322 non-null    object
dtypes: float64(3), int64(1), object(4)
memory usage: 20.3+ KB

Missing Values
amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

Duplicate Rows
0

In [58]:
holdings["portfolio_date"] = pd.to_datetime(holdings["portfolio_date"])

In [59]:
holdings = holdings[ (holdings["weight_pct"] >= 0) & (holdings["weight_pct"] <= 100)]

In [60]:
holdings = holdings[ (holdings["market_value_cr"] > 0) & (holdings["current_price_inr"] > 0)]

In [61]:
holdings.to_csv("data/processed/clean_portfolio_holdings.csv", index=False)

### benchmark_indices.csv

In [62]:
benchmark = pd.read_csv("data/raw/10_benchmark_indices.csv")

print(benchmark.columns)

Index(['date', 'index_name', 'close_value'], dtype='object')

In [63]:
benchmark.info()

print("\nMissing Values")
print(benchmark.isnull().sum())

print("\nDuplicate Rows")
print(benchmark.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8050 entries, 0 to 8049
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         8050 non-null   object
 1   index_name   8050 non-null   object
 2   close_value  8050 non-null   float64
dtypes: float64(1), object(2)
memory usage: 188.8+ KB

Missing Values
date           0
index_name     0
close_value    0
dtype: int64

Duplicate Rows
0

In [64]:
benchmark["date"] = pd.to_datetime(benchmark["date"])

In [65]:
benchmark.to_csv("data/processed/clean_benchmark.csv", index=False)

### fund_master.csv

In [66]:
fund = pd.read_csv("data/raw/01_fund_master.csv")

fund.info()

print("\nMissing Values")
print(fund.isnull().sum())

print("\nDuplicate Rows")
print(fund.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     object
 2   scheme_name         40 non-null     object
 3   category            40 non-null     object
 4   sub_category        40 non-null     object
 5   plan                40 non-null     object
 6   launch_date         40 non-null     object
 7   benchmark           40 non-null     object
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     object
 13  risk_category       40 non-null     object
 14  sebi_category_code  40 non-null     object
dtypes: float64(2), int64(3), object(10)
memory usage: 4.8+ KB

Missing Values
amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

Duplicate Rows
0

In [67]:
fund["launch_date"] = pd.to_datetime(fund["launch_date"])

In [68]:
fund.to_csv("data/processed/clean_fund_master.csv", index=False)

### --------------------------------------------------------------------------------------

In [69]:
import sqlite3

conn = sqlite3.connect("bluestock_mf.db")

print("Database created successfully!")

Database created successfully!

In [70]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("sqlite:///bluestock_mf.db")

In [71]:
fund = pd.read_csv("data/processed/clean_fund_master.csv")
nav = pd.read_csv("data/processed/clean_nav.csv")
aum = pd.read_csv("data/processed/clean_aum.csv")
sip = pd.read_csv("data/processed/clean_sip_inflows.csv")
category = pd.read_csv("data/processed/clean_category_inflows.csv")
folio = pd.read_csv("data/processed/clean_folio_count.csv")
performance = pd.read_csv("data/processed/clean_performance.csv")
transactions = pd.read_csv("data/processed/clean_transactions.csv")
holdings = pd.read_csv("data/processed/clean_portfolio_holdings.csv")
benchmark = pd.read_csv("data/processed/clean_benchmark.csv")

In [72]:
fund.to_sql("dim_fund", engine, if_exists="replace", index=False)

nav.to_sql("fact_nav", engine, if_exists="replace", index=False)

aum.to_sql("fact_aum", engine, if_exists="replace", index=False)

sip.to_sql("fact_sip", engine, if_exists="replace", index=False)

category.to_sql("fact_category", engine, if_exists="replace", index=False)

folio.to_sql("fact_folio", engine, if_exists="replace", index=False)

performance.to_sql("fact_performance", engine, if_exists="replace", index=False)

transactions.to_sql("fact_transactions", engine, if_exists="replace", index=False)

holdings.to_sql("fact_holdings", engine, if_exists="replace", index=False)

benchmark.to_sql("fact_benchmark", engine, if_exists="replace", index=False)

print("All datasets loaded successfully!")

All datasets loaded successfully!

In [73]:
connection = sqlite3.connect("bluestock_mf.db")

query = "SELECT name FROM sqlite_master WHERE type='table';"

tables = pd.read_sql(query, connection)

tables

                name
0           dim_fund
1           fact_nav
2           fact_aum
3           fact_sip
4      fact_category
5         fact_folio
6   fact_performance
7  fact_transactions
8      fact_holdings
9     fact_benchmark